export interface Empleado {
  id: Number; //": 1,
  rut: String; //": "rut-empleado-0",
  nombre: String; //": "Empleado 0",
  correo: String; //": "empleado0@empresa.com",
  password: String; //": "password0",
  telefono: String; //": "+56000000000",
  persona_juridica_id: Number; //": 1
}

export interface RepresentanteLegal {
  id: Number; // 1,
  rut: String; // "rut-rl-0",
  nombre: String; // "Representante Legal 0",
  telefono: String; // "+56000000000",
  correo: String; // "rl0@empresa.com",
  persona_juridica_id: Number; // 1
}

export interface PersonaJuridica {
  id: Number;
  rut: String | null;
  nombre: String | null;
  domicilio: String | null;
  comuna: String | null;
  ciudad: String | null;
  constitucion: String;
  telefono: String;
  tipo_sociedad: String;
  empleados: Empleado[];
  representante_legal: RepresentanteLegal[];
}

export interface ControlEfectivo {
  id: Number;
  nombre_completo: String;
  rut_identificacion: String;
  participacion: String;
  declaracion_id: Number;
}

export interface BeneficiarioFinal {
  id: Number;
  nombre_completo: String;
  rut_identificacion: String;
  participacion: String;
  declaracion_id: Number;
}

export interface Declaracion {
  id: Number;
  folio: String;
  fecha_declaracion: Date;
  fecha_carga_declaracion: Date;
  is_active: Boolean;
  persona_juridica_id: Number;
  beneficiarios_finales: BeneficiarioFinal[] | null;
  control_efectivo: ControlEfectivo[] | null;
  persona_juridica: PersonaJuridica;
}

export interface PJuridicas {
  registro_id: number;
  id?: string;
  rut_no?: string;
  razon_social?: string;
  domicilio?: string;
  ciudad?: string;
  lugar_de_constitucion?: string;
  telefono?: string;
  cni_no?: string;
  nombre_rep_legal?: string;
  tipo_sociedad?: string;
  codigo_banco?: string;
  correlativo_declaracion?: string;
  codigo_institucion?: string;
  fecha_envio_archivo?: string;
  correlativo?: string;
  archivo_fuente?: string;
  tipo_archivo?: string;
  fechahora_transformacion?: string;
  fechahora_creacion?: Date;
}
export type PersonasJuridicas = {
  id: string; // BigInt cambiado a string
  rut?: string | null; // Opcional y puede ser null
  razon_social?: string | null; // Opcional y puede ser null
  domicilio?: string | null; // Opcional y puede ser null
  ciudad?: string | null; // Opcional y puede ser null
  lugar_de_constitucion?: string | null; // Opcional y puede ser null
  telefono?: string | null; // Opcional y puede ser null
  identificacion_rep_legal?: string | null; // Opcional y puede ser null
  nombre_rep_legal?: string | null; // Opcional y puede ser null
  tipo_de_sociedad?: string | null; // Opcional y puede ser null
  created_at?: string | null; // DateTime convertido a string, opcional y puede ser null
  declaracion_id: string; // BigInt cambiado a string
  // bf_data_process_declaraciones?: BfDataProcessDeclaraciones; // Dependiendo de cómo esté definido este tipo
};

type BfDataProcessBeneficiariosFinales = {
  id: string; // BigInt cambiado a string
  tipo?: string | null; // Opcional y puede ser null
  identificacion?: string | null; // Opcional y puede ser null
  nombre_completo?: string | null; // Opcional y puede ser null
  domicilio?: string | null; // Opcional y puede ser null
  ciudad?: string | null; // Opcional y puede ser null
  pais?: string | null; // Opcional y puede ser null
  participacion?: string | null; // Opcional y puede ser null
  created_at?: string | null; // DateTime convertido a string, opcional y puede ser null
  declaracion_id: string; // BigInt cambiado a string
  // bf_data_process_declaraciones?: BfDataProcessDeclaraciones; // Dependiendo de cómo esté definido este tipo
};
export type BfDataProcessDeclaraciones = {
  id: string; // Cambiado de BigInt a string
  codigo_banco?: string | null; // Opcional y puede ser null
  correlativo?: string | null; // Opcional y puede ser null
  status?: string | null; // Opcional y puede ser null
  fecha_subida?: string | null; // DateTime convertido a string, opcional y puede ser null
  num_declaracion?: string | null; // Opcional y puede ser null
  fecha_declaracion?: string | null; // DateTime convertido a string, opcional y puede ser null
  bank_id: string; // Cambiado de BigInt a string
  // Los siguientes campos representan relaciones y dependen de cómo desees manejarlas en TypeScript.
  bf_data_process_beneficiariosfinales?: BfDataProcessBeneficiariosFinales[]; // Dependiendo de cómo esté definido este tipo
  // bf_data_process_bank?: BfDataProcessBank; // Dependiendo de cómo esté definido este tipo
  bf_data_process_personasjuridicas?: PersonasJuridicas[]; // Dependiendo de cómo esté definido este tipo
};


export interface PFinales {
  registro_id: number; // Autogenerated, no need to be optional
  id?: string;
  cni_id_rut_benef_final?: string;
  nombre_completo?: string;
  domicilio?: string;
  ciudad?: string;
  pais?: string;
  tipo_beneficiario_final?: string;
  porc_participacion?: string;
  cni_id_rut_persona_juridica?: string;
  codigo_banco?: string;
  correlativo_declaracion?: string;
  codigo_institucion?: string;
  fecha_envio_archivo?: string;
  correlativo?: string;
  archivo_fuente?: string;
  tipo_archivo?: string;
  fechahora_transformacion?: string;
  fechahora_creacion?: Date; // Assuming this should be a Date object in TypeScript
}

export interface BfDataProcessFilelog {
  id: number; // o number, si no necesitas manejar enteros grandes
  file_name?: string;
  file_path?: string;
  full_filePath?: string;
  created_at?: Date;
  updated_at?: Date;
  codigo_banco?: string;
  errors: boolean;
  message?: string;
}